//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorizeDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.TokenIssueds = new HashSet<TokenIssued>();
            this.Clipboards = new HashSet<Clipboard>();
        }
    
        public long Id { get; set; }
        public string Uname { get; set; }
        public string HashSaltBase64 { get; set; }
        public int HashTypeId { get; set; }
        public string PasswordHashBase64 { get; set; }
        public bool IsTwoFactor { get; set; }
        public string TwoFactorSecretBase32 { get; set; }
    
        public virtual HashType HashType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TokenIssued> TokenIssueds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clipboard> Clipboards { get; set; }
    }
}
