//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorizeDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenIssued
    {
        public long AccountId { get; set; }
        public string Val { get; set; }
        public System.DateTime IssuedAtUtc { get; set; }
        public System.DateTime ExpireAtUtc { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
